### ISSUE TITLE
Some links in Subtitle Overview are invalid

### ISSUE THREAD

**Issue by 3gf8jv4dv** [MingYSub/SubsArchive#12]
| Invalid Link | Correct Link |
| :-- | :-- |
| `https://raw.githubusercontent.com/MingYSub/SubsArchive/main/Archive/Hokkyoku%20Hyakkaten%20no%20Concierge-san` | `https://github.com/MingYSub/SubsArchive/tree/main/Archive/Hokkyoku%20Hyakkaten%20no%20Concierge-san` |
| `https://raw.githubusercontent.com/MingYSub/SubsArchive/main/Archive/Senpai%20wa%20Otokonoko` | `https://github.com/MingYSub/SubsArchive/tree/main/Archive/Senpai%20wa%20Otokonoko` |
| `https://github.com/MingYSub/SubsArchive/tree/main/Archive/Do%20It%20Yourself` | `https://github.com/MingYSub/SubsArchive/tree/main/Archive/Do%20It%20Yourself%21%21` |
| `https://github.com/MingYSub/SubsArchive/tree/main/Archive/Bocchi%20the%20Rock` | `https://github.com/MingYSub/SubsArchive/tree/main/Archive/Bocchi%20the%20Rock%21` |

*By the way. Among the remaining GitHub links, some include `blob` and some include `tree`. Could we use the latter uniformly? Because GitHub will automatically redirect to a link containing the latter when accessing a link containing the former.*

**Comment by MingYSub** [comment]
Thanks for reporting. All links have been corrected.

**Comment by MingYSub** [comment]
> This is a troublesome question. The `!` will not be converted to `%21` when copying the link as URL, however GitHub Projects will only recognize the latter. This happened to our fellow industry player KitaujiSub.

Fixed. Still, for new animes, we will consider using abbreviations (if there are official ones) and also avoid special characters like `?!:.,`.
